### ISSUE TITLE
PG::InvalidParameterValue: ERROR:  unrecognized intdict parameter: "absval"

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#167]
After the last DB update by @vishal-bluebash I get this error on `bin/rake db:migrate` and `bundle exec rake db:structure:load`:

```
StandardError: An error has occurred, this and all later migrations canceled:

PG::InvalidParameterValue: ERROR:  unrecognized intdict parameter: "absval"
: CREATE TEXT SEARCH CONFIGURATION public.cv_en ( COPY = pg_catalog.english ); CREATE TEXT SEARCH DICTIONARY cv_en_intdict ( TEMPLATE = intdict_template ); ALTER TEXT SEARCH DICTIONARY cv_en_intdict (MAXLEN = 12, ABSVAL=true); ALTER TEXT SEARCH CONFIGURATION cv_en ALTER MAPPING FOR int, uint WITH cv_en_intdict; CREATE TEXT SEARCH CONFIGURATION public.cv_it ( COPY = pg_catalog.italian ); CREATE TEXT SEARCH DICTIONARY cv_it_intdict ( TEMPLATE = intdict_template ); ALTER TEXT SEARCH DICTIONARY cv_it_intdict (MAXLEN = 12, ABSVAL=true); ALTER TEXT SEARCH CONFIGURATION cv_it ALTER MAPPING FOR int, uint WITH cv_it_intdict;
/Users/duccioarmenise/dev/rails/publicv/db/migrate/20210506190331_add_int_dict_configrations.rb:4:in `block in up'
/Users/duccioarmenise/dev/rails/publicv/db/migrate/20210506190331_add_int_dict_configrations.rb:3:in `up'
-e:1:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::InvalidParameterValue: ERROR:  unrecognized intdict parameter: "absval"
: CREATE TEXT SEARCH CONFIGURATION public.cv_en ( COPY = pg_catalog.english ); CREATE TEXT SEARCH DICTIONARY cv_en_intdict ( TEMPLATE = intdict_template ); ALTER TEXT SEARCH DICTIONARY cv_en_intdict (MAXLEN = 12, ABSVAL=true); ALTER TEXT SEARCH CONFIGURATION cv_en ALTER MAPPING FOR int, uint WITH cv_en_intdict; CREATE TEXT SEARCH CONFIGURATION public.cv_it ( COPY = pg_catalog.italian ); CREATE TEXT SEARCH DICTIONARY cv_it_intdict ( TEMPLATE = intdict_template ); ALTER TEXT SEARCH DICTIONARY cv_it_intdict (MAXLEN = 12, ABSVAL=true); ALTER TEXT SEARCH CONFIGURATION cv_it ALTER MAPPING FOR int, uint WITH cv_it_intdict;
/Users/duccioarmenise/dev/rails/publicv/db/migrate/20210506190331_add_int_dict_configrations.rb:4:in `block in up'
/Users/duccioarmenise/dev/rails/publicv/db/migrate/20210506190331_add_int_dict_configrations.rb:3:in `up'
-e:1:in `<main>'

Caused by:
PG::InvalidParameterValue: ERROR:  unrecognized intdict parameter: "absval"
/Users/duccioarmenise/dev/rails/publicv/db/migrate/20210506190331_add_int_dict_configrations.rb:4:in `block in up'
/Users/duccioarmenise/dev/rails/publicv/db/migrate/20210506190331_add_int_dict_configrations.rb:3:in `up'
-e:1:in `<main>'
Tasks: TOP => db:migrate

```

If needed, we should also add instructions into README to correctly set up the development environment without running into this issue.

**Comment by vishal-bluebash** [comment]
@darmenise please upgrade to 13+ Postgres ,it will be solved

**Comment by darmenise** [comment]
Ok, please add this requirement to README.md 😄
